#!/usr/bin/env bash
# Evopet installer: registers Evopet with claude-config's optional-projects
# shim system, merges statusLine.command into ~/.claude/settings.json, and
# wires ~/.bash_profile. Idempotent.
set -euo pipefail

EVO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOCAL_DIR="$HOME/.claude/local"
SHIM_FILE="$LOCAL_DIR/optional-projects.sh"
BASH_PROFILE="$HOME/.bash_profile"
SETTINGS_FILE="$HOME/.claude/settings.json"
SHIM_LINE='[ -f "$HOME/.claude/local/optional-projects.sh" ] && . "$HOME/.claude/local/optional-projects.sh"'

mkdir -p "$LOCAL_DIR"

# Write shim using literal heredoc, then sed-replace placeholder.
cat > "$SHIM_FILE" <<'EOF'
# Auto-generated by evopet-install.sh
: "${EVOPET_ENABLED:=1}"
[ "${DISABLE_OPTIONAL_PROJECTS:-0}" = "1" ] && return 0
[ "$EVOPET_ENABLED" = "1" ] || return 0
EVO_BIN="<EVO_ROOT_PLACEHOLDER>/bin"
[ -d "$EVO_BIN" ] || return 0
case ":$PATH:" in
  *":$EVO_BIN:"*) ;;
  *) export PATH="$EVO_BIN:$PATH" ;;
esac
export EVO_HOME="<EVO_ROOT_PLACEHOLDER>"
EOF

# Replace placeholder with actual EVO_ROOT (use | as sed delimiter to avoid / clashes).
sed -i "s|<EVO_ROOT_PLACEHOLDER>|${EVO_ROOT}|g" "$SHIM_FILE"

# Wire .bash_profile (idempotent).
touch "$BASH_PROFILE"
if grep -F "$SHIM_LINE" "$BASH_PROFILE" > /dev/null 2>&1; then
  echo "[evopet-install] .bash_profile already wired, skipping"
else
  printf '\n# Evopet optional-projects shim\n%s\n' "$SHIM_LINE" >> "$BASH_PROFILE"
  echo "[evopet-install] wired .bash_profile"
fi

# Merge statusLine.command into ~/.claude/settings.json via Node.
mkdir -p "$(dirname "$SETTINGS_FILE")"
[ -f "$SETTINGS_FILE" ] || echo '{}' > "$SETTINGS_FILE"

node -e '
const fs = require("fs");
const path = process.argv[1];
let obj = {};
try { obj = JSON.parse(fs.readFileSync(path, "utf8") || "{}"); } catch (e) {
  console.error("[evopet-install] settings.json parse failed: " + e.message);
  process.exit(1);
}
const desired = { type: "command", command: "python ~/.claude/base_statusline.py" };
const cur = obj.statusLine;
if (cur && cur.type === desired.type && cur.command === desired.command) {
  console.log("[evopet-install] settings.json statusLine already correct, skipping");
} else {
  obj.statusLine = desired;
  fs.writeFileSync(path, JSON.stringify(obj, null, 2) + "\n");
  console.log("[evopet-install] settings.json statusLine merged");
}
' "$SETTINGS_FILE"

echo "[evopet-install] complete. Open a new shell to activate. Set EVOPET_ENABLED=0 to disable."
