#!/usr/bin/env bash
# Evopet installer: registers Evopet with claude-config's optional-projects
# shim system, merges statusLine.command into ~/.claude/settings.json, and
# wires ~/.bash_profile. Idempotent.
set -euo pipefail

EVO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOCAL_DIR="$HOME/.claude/local"
SHIM_FILE="$LOCAL_DIR/optional-projects.sh"
BASH_PROFILE="$HOME/.bash_profile"
SETTINGS_FILE="$HOME/.claude/settings.json"
SHIM_LINE='[ -f "$HOME/.claude/local/optional-projects.sh" ] && . "$HOME/.claude/local/optional-projects.sh"'

mkdir -p "$LOCAL_DIR"

# Write shim using literal heredoc — emits a dynamic resolver (no hardcoded
# absolute path) so the same generated file works across PCs and npm-only
# deployments.
cat > "$SHIM_FILE" <<'EOF'
# Auto-generated by evopet-install.sh — dynamic resolver.
# Priority:
#   1. evo already in PATH (npm install -g, prior setup, manual)
#   2. Windows npm prefix: $APPDATA/npm/evo.cmd or ~/AppData/Roaming/npm
#   3. Unix npm prefix: $(npm bin -g)/evo
#   4. EVOPET_LOCAL_BIN env override
#   5. Auto-search: $HOME/Documents/PythonScripts/*/evolutionary-cli-wrapper/bin
[ "${DISABLE_OPTIONAL_PROJECTS:-0}" = "1" ] && return 0
[ "${EVOPET_ENABLED:-1}" = "1" ] || return 0

command -v evo >/dev/null 2>&1 && return 0

_evo_candidate=""
# Windows: .cmd files are executable by extension, not POSIX bit, so use -f.
if [ -n "${APPDATA:-}" ] && [ -f "$APPDATA/npm/evo.cmd" ]; then
  _evo_candidate="$APPDATA/npm"
elif [ -d "$HOME/AppData/Roaming/npm" ] && [ -f "$HOME/AppData/Roaming/npm/evo.cmd" ]; then
  _evo_candidate="$HOME/AppData/Roaming/npm"
fi
if [ -z "$_evo_candidate" ] && command -v npm >/dev/null 2>&1; then
  _npm_bin="$(npm bin -g 2>/dev/null || true)"
  [ -n "$_npm_bin" ] && [ -x "$_npm_bin/evo" ] && _evo_candidate="$_npm_bin"
fi
if [ -z "$_evo_candidate" ] && [ -n "${EVOPET_LOCAL_BIN:-}" ] && [ -d "$EVOPET_LOCAL_BIN" ]; then
  _evo_candidate="$EVOPET_LOCAL_BIN"
fi
if [ -z "$_evo_candidate" ]; then
  for _d in "$HOME"/Documents/PythonScripts/*/evolutionary-cli-wrapper/bin; do
    [ -d "$_d" ] && _evo_candidate="$_d" && break
  done
fi
[ -z "$_evo_candidate" ] && return 0
case ":$PATH:" in
  *":$_evo_candidate:"*) ;;
  *) export PATH="$_evo_candidate:$PATH" ;;
esac
if [ -d "$_evo_candidate/../.git" ] || [ -f "$_evo_candidate/../package.json" ]; then
  export EVO_HOME="$(cd "$_evo_candidate/.." && pwd)"
fi
unset _evo_candidate _d _npm_bin
EOF

# Wire .bash_profile (idempotent).
touch "$BASH_PROFILE"
if grep -F "$SHIM_LINE" "$BASH_PROFILE" > /dev/null 2>&1; then
  echo "[evopet-install] .bash_profile already wired, skipping"
else
  printf '\n# Evopet optional-projects shim\n%s\n' "$SHIM_LINE" >> "$BASH_PROFILE"
  echo "[evopet-install] wired .bash_profile"
fi

# Merge statusLine.command into ~/.claude/settings.json via Node.
mkdir -p "$(dirname "$SETTINGS_FILE")"
[ -f "$SETTINGS_FILE" ] || echo '{}' > "$SETTINGS_FILE"

node -e '
const fs = require("fs");
const path = process.argv[1];
let obj = {};
try { obj = JSON.parse(fs.readFileSync(path, "utf8") || "{}"); } catch (e) {
  console.error("[evopet-install] settings.json parse failed: " + e.message);
  process.exit(1);
}
const desired = { type: "command", command: "python ~/.claude/base_statusline.py" };
const cur = obj.statusLine;
if (cur && cur.type === desired.type && cur.command === desired.command) {
  console.log("[evopet-install] settings.json statusLine already correct, skipping");
} else {
  obj.statusLine = desired;
  fs.writeFileSync(path, JSON.stringify(obj, null, 2) + "\n");
  console.log("[evopet-install] settings.json statusLine merged");
}
' "$SETTINGS_FILE"

echo "[evopet-install] complete. Open a new shell to activate. Set EVOPET_ENABLED=0 to disable."
